spring:
  ai:
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        initialize-schema: true # auto gen collection
        collection-name: springAi
