spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # for local test allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/jpashop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # or org.hibernate.dialect.MySQLDialect for older versions
    hibernate:
      ddl-auto: update
    show-sql: false # 콘솔 창에 출력

logging:
  level:
    org.hibernate.sql: debug # 로거에 출력


## SPRING AI ##
# Chat Memory Config
  # ai:
  #   chat:
  #     memory:
  #       repository:
  #         jdbc:
  #           initialize-schema: never

# implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
# implementation 'com.mysql:mysql-connector-j'
#  <dependency>
#   <groupId>com.mysql</groupId>
#   <artifactId>mysql-connector-j</artifactId>
#   <scope>runtime</scope> </dependency>
#  </dependencies>

# implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc'

