spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/your-database
    username: mysql
    password: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

# implementation 'mysql:mysql-connector-java:8.0.33'
# <dependency>
#    <groupId>mysql</groupId>
#    <artifactId>mysql-connector-java</artifactId>
#    <version>8.0.33</version>
# </dependency>
