spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # for local test allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/<your_database_name>?useSSL=false&serverTimezone=UTC
    username: <your_username>
    password: <your_password>
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # or org.hibernate.dialect.MySQLDialect for older versions
    hibernate:
      ddl-auto: update
    show-sql: false
  # Chat Memory Config
  # ai:
  #   chat:
  #     memory:
  #       repository:
  #         jdbc:
  #           initialize-schema: never

# implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
# implementation 'com.mysql:mysql-connector-j'
#  <dependency>
#   <groupId>com.mysql</groupId>
#   <artifactId>mysql-connector-j</artifactId>
#   <scope>runtime</scope> </dependency>
#  </dependencies>

# implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc'

