spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      # these are default values
      init:
        pull-model-strategy: never
        timeout: 5m
        max-retries: 0
        chat:
          options:
            model: gemma3:1b
          include: true
          additional-models:
            - []
      embedding:
        enabled: true
        options:
          model: jeffh/intfloat-multilingual-e5-large-instruct:f16

model:
  embeddingSize: 1024
# implementation platform("org.springframework.ai:spring-ai-bom:1.0.0-SNAPSHOT")
# implementation("org.springframework.ai:spring-ai-ollama")

#   <dependency>
#     <groupId>org.springframework.ai</groupId>
#     <artifactId>spring-ai-bom</artifactId>
#     <version>1.0.0-SNAPSHOT</version>
#     <type>pom</type>
#     <scope>import</scope>
#   </dependency>

#  <dependency>
#  <groupId>org.springframework.ai</groupId>
#  <artifactId>spring-ai-starter-model-ollama</artifactId>
#  </dependency>

#  maven { url 'https://repo.spring.io/milestone' }
#  maven { url 'https://repo.spring.io/snapshot' }
#  maven {
#  name = 'Central Portal Snapshots'
#  url = 'https://central.sonatype.com/repository/maven-snapshots/'
#  }}
