spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      # these are default values
      init:
        pull-model-strategy: never
        timeout: 5m
        max-retries: 0
        chat:
          include: true
          additional-models:
            - [ ]
      embedding:
        enabled: true
        options:
          model: jeffh/intfloat-multilingual-e5-large-instruct:f16

model:
  embeddingSize: 1024