spring:
  ai:
    openai:
      api-key: "<your-api-key-here>"
      chat:
        options:
          model: 'gpt-4o-mini' # 모델명
          temperature: 0.8 # 모델의 창의력 0 ~ 1
      embedding:
        options:
          model: 'text-embedding-3-small' # token: 8192 dim: 1536


#implementation 'org.springframework.ai:spring-ai-starter-model-openai'

#dependencyManagement {
#  imports {
#     mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
#  }
#}
