spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:<filePath>
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
