version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
